
// Objective-C API for talking to the following Go packages
//
//	gomobiletest/go/greeter
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Greeter_FRAMEWORK_H__
#define __Greeter_FRAMEWORK_H__

#include "Greeter.objc.h"
#include "Universe.objc.h"

#endif
